# -*- coding: utf-8 -*-
"""PROJECT-3-Sentiment Analysis using NLP and Deep Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEnYzpQQODrT99H9FRJhUHRlaYGilm7s
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("movie_reviews.csv")

df.head()

df.shape

# Handling missing values

df.isnull().sum()

df = df.dropna(subset=["review_text","sentiment"])

df.shape

# droping dublicates

df.duplicated().sum()

df=df.drop_duplicates()

df.shape

df.info()

"""**TEXT PREPROCESSING**"""

# Remove special characters

import re

df["clean_review"] = df["review_text"].str.replace("[^a-zA-Z0-9\s]", " ")

# lowercasing

df["clean_review"] = df["review_text"].str.lower()

df["clean_review"]

# tokenization

import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

tokenized_review = []

for sentence in df["clean_review"]:

  words = word_tokenize(sentence)

  tokenized_review.append(words)
df["tokenized_review"] = tokenized_review

print(df["tokenized_review"].head())

# remove stopwords

from nltk.corpus import stopwords
import nltk

nltk.download('stopwords')

stop_words = set(stopwords.words("english"))

filtered_review = []

for words_list in df["tokenized_review"]:

  new_sentence = []

  for word in words_list:

    if word.lower() not in stop_words:

      new_sentence.append(word)

  filtered_review.append(new_sentence)

df["filtered_review"] = filtered_review

print(df["filtered_review"].head())

# Lemmatization

import spacy

nlp = spacy.load("en_core_web_sm")

lemmatized_review = []

for words in df["filtered_review"]:

    text = " ".join(words)

    doc = nlp(text)

    new_words = []

    for token in doc:

        new_words.append(token.lemma_)

    lemmatized_review.append(" ".join(new_words))

df["clean_review"] = lemmatized_review

print(df["clean_review"].head())

"""**TF-IDF**"""

from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd


tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(df["clean_review"])

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=tfidf_vectorizer.get_feature_names_out()
)


print(df.head())

x = tfidf_df
y = df["sentiment"]

"""**TRAIN-TEST-SPLIT**"""

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

x_train.shape

y_train.shape

x_test.shape

y_test.shape

"""**ANN MODEL **"""

import tensorflow as tf

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense, Dropout

from tensorflow.keras.callbacks import EarlyStopping

model = Sequential()

#input layer
model.add(Dense(128, activation="relu"))

#hidden layer
model.add(Dense(64, activation="relu"))

#dropout layer
model.add(Dropout(0.5))

#outer layer
model.add(Dense(1, activation="sigmoid"))

# model summary

model.summary()

# compile the model

model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# train the model

history = model.fit(x_train, y_train, epochs=10)

# evaluate the model

loss, accuracy = model.evaluate(x_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

# predictions

predictions = model.predict(x_test)

print(predictions)

# accuracy score

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions.round())

print("Accuracy:", accuracy)

# precision score

from sklearn.metrics import precision_score

precision = precision_score(y_test, predictions.round())

print("Precision:", precision)

# recall score

from sklearn.metrics import recall_score

recall = recall_score(y_test, predictions.round())

print("Recall:", recall)

# f1 score

from sklearn.metrics import f1_score

f1 = f1_score(y_test, predictions.round())

print("F1 Score:", f1)

# confusion matrix

from sklearn.metrics import confusion_matrix

confusion_matrix = confusion_matrix(y_test, predictions.round())

print("Confusion Matrix:")
print(confusion_matrix)

# classification report

from sklearn.metrics import classification_report

classification_report = classification_report(y_test, predictions.round())

print("Classification Report:")
print(classification_report)

"""**CONFUSION MATRIX**"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6,5))

sns.heatmap(confusion_matrix,
            annot=True,
            fmt="d",
            cmap="Blues")

plt.xlabel("Predicted")

plt.ylabel("Actual")

plt.title("Confusion Matrix")

plt.show()

"""**ACCURACY GRAPH**"""

plt.figure(figsize=(8,6))
plt.plot(history.history["accuracy"], label="Training Accuracy")



plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title(" Accuracy Graph ")

plt.legend()

plt.show()

"""**LOSS GRAPH**"""

plt.figure(figsize=(8,5))

plt.plot(history.history["loss"], label="Training Loss")


plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title(" Loss Graph")
plt.legend()

plt.show()

print(df.shape)

# sentiment distribution

print(y.value_counts())

sentiment_df = pd.DataFrame({'sentiment': y})
sns.countplot(x="sentiment", data=sentiment_df)
plt.title("Sentiment Distribution")
plt.show()

# Predict on test data
y_pred = (model.predict(x_test) > 0.5).astype(int).flatten()

# Get original reviews corresponding to x_test
test_reviews = df.loc[x_test.index, "review_text"]

results = pd.DataFrame({
    "Review": test_reviews,
    "Actual": y_test,
    "Predicted": y_pred
})

print("Correct Predictions")
print(results[results["Actual"] == results["Predicted"]].head(2))

print("\nWrong Predictions")
print(results[results["Actual"] != results["Predicted"]].head(2))